// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyManagement.Infrastructure.Persistence;

#nullable disable

namespace PolicyManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyManagement.Domain.Entities.Policy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PolicyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("FlaggedForReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyholderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Underwriter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Policies");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Policies_CreatedAt");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_Policies_EffectiveDate");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_Policies_ExpiryDate");

                    b.HasIndex("FlaggedForReview")
                        .HasDatabaseName("IX_Policies_FlaggedForReview");

                    b.HasIndex("LineOfBusiness")
                        .HasDatabaseName("IX_Policies_LineOfBusiness");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Policies_PolicyNumber_U");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Policies_Region");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Policies_Status");

                    b.ToTable("Policies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
